### ISSUE TITLE
Get rid of OpenSSL

### ISSUE THREAD

**Issue by rbost** [OpenSSE/crypto-tk#4]
Now that libsodium is used in the cryptographic toolkit since the merge of PR #3, we should try to remove all the dependencies to OpenSSL. Also, OpenSSL is actually terrible so it is not a bad idea in terms of security.

For symmetric key primitives, we can directly use libsodium's API. For asymmetric crypto, there are two primitives, trapdoor permutations and incremental hashing. 

For TDP, we can embed mbedTLS' implementation. For elliptic curve multiset hash, we will have to wait for the implementation of Elligator2 in libsodium (cf. jedisct1/libsodium#628).

**Comment by mankash** [comment]
Hello @rbost -

Is it possible to use hardware accelerated modules in mbedTls for higher performance?
Please see a list of hash, symmetric and asymmetric primitives already accelerated:
http://bit.ly/2i8GukJ

Will that speed up Sophos' rsa tdp private key operations?

**Comment by rbost** [comment]
Yes. But, we will use mbedTLS only for RSA (which cannot be hardware accelerated), not for the rest of the primitives (it will be libsodium).

As the TDP will not be used in practice for the most efficient SSE schemes, so I do not see this as a real limitation. Do you actually need it?

**Comment by mankash** [comment]
It'd be interesting to benchmark sophos' performance with an accelerated RSA TDP.  Sophos' beauty lies in it's simplicity - as a self taught SSE novice I was able to comprehend the theory behid it compared to most other constructions, even Diana. I suppose from a practical viewpoint, I'll have to work through the CRPRF innards to really understand Diana. 

Thanks for all of your work BTW - the papers, presentations, videos and code all add up to a really valuable online course in cutting edge SSE

**Comment by rbost** [comment]
OK, I will probably leave both implementations. mdedTLS will be used by default, and the OpenSSL implementation will still be available.

You should really look at Diana, it is not very complicated in the end 😃.

**Comment by rbost** [comment]
OpenSSL is no longer necessary to build the OpenSSE cryptography toolkit since commit 74942b97815b7da5fb8f7096d5d31326769171e6.
OpenSSL is still used in an implementation of the trapdoor permutation, but, by default, an embedded mbedTLS-based implementation is used.
